name: CI
on:
  push:
    branches:
      - main
      - docker-test-fail
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:

  native-static-tests-1:
    timeout-minutes: 120
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: VirtusLab/scala-cli-setup@49e973f40321361e27fe0847308da6d4f6461a45
        with:
          jvm: "temurin:17"
      - name: Build docker image
        run: .github/scripts/generate-docker-image.sh
      - name: Docker integration tests
        run: ./mill integration.docker.test
